FROM ubuntu:latest
MAINTAINER Josh

RUN apt-get update -y \
&& apt-get install -y wget 

WORKDIR /opt/
RUN wget https://www15.software.ibm.com/sdfdl/v2/fulfill/CNEM6EN/Xa.2/Xb.aFmQQe8PD7-rdHhER0-tBrn8HyHCX2doZ4xBOS4nMOM/Xc.CNEM6EN/UBCD_BD_6.2.2_LINUX_ON_POWER_TRIA.tgz/Xd./Xf.LPR.F1AZ/Xg.8911561/Xi.RATLe-UCDeploy-EVAL/XY.regsrvs/XZ.DuIjUNF8Qlytnrkz2n_69loPZMc/UBCD_BD_6.2.2_LINUX_ON_POWER_TRIA.tgz
